// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEctdnxeQOaYIRC49hU_97UqesO4qs4Ws',
    appId: '1:205040157:web:85c0412db62928d20234f4',
    messagingSenderId: '205040157',
    projectId: 'ekobek',
    authDomain: 'ekobek.firebaseapp.com',
    storageBucket: 'ekobek.firebasestorage.app',
    measurementId: 'G-2BRBR2JH9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Wwmn_a2TswEifd_dAWHM6UmlGc9hAqA',
    appId: '1:205040157:android:5c4b3f1ed6730f850234f4',
    messagingSenderId: '205040157',
    projectId: 'ekobek',
    storageBucket: 'ekobek.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB58CoGVrGQztsgHfDnCAaRaVx4EGVJT7E',
    appId: '1:205040157:ios:678dcbde9994a0b30234f4',
    messagingSenderId: '205040157',
    projectId: 'ekobek',
    storageBucket: 'ekobek.firebasestorage.app',
    iosBundleId: 'com.example.ekobek',
  );
}
